version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    restart: always
